export const actions = {
  profile: {
    DATA_FESSING: "PROFILE_DATA_FESSING",
    DATA_FESSING_SUCCESS: "PROFILE_DATA_FESSING_SUCCESS",
    DATA_FESSING_ERROR: "PROFILE_DATA_FESSING_ERROR",
    USER_DATA_UPDATE: "PROFILE_USER_DATA_UPDATE",
    IMAGE_UPDATE: "PROFILE_IMAGE_UPDATE",
  },
};
